name: " cattle_ru's blog"
description: "牛业的个人博客"

avatar: 
#页面图像
favicon:
#网页图标

navigation:
  - name: 首页
    url: /
  - name: 关于我
    url: /about
  - name: 奇怪的东西
    url: /tags

paginate: 8

excerpt_separator: <!-- more -->

footer-links:
  zhihu: 瑞斯到处跑
  email: yao357753@163.com
  facebook:
  github: cattleru
  rss: # just type anything here for a working RSS icon
  twitter: lian20082
  youtube:

footer-text: 2025 cattle_ru
url: https://cattleru.github.io

permalink: /:title/
paginate_path: /page:num/

# The release of Jekyll Now
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

